trigger:
- main  # Adjust this to your default branch

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  azureSubscription:
  appName: 'lonwebapp'
  resourceGroupName: 'az400'

steps:
- script: |
    dotnet restore WebService/WebService.sln
  displayName: 'Restore NuGet Packages'

- script: |
    dotnet build WebService/WebService.sln --configuration $(buildConfiguration)
  displayName: 'Build Solution'

- script: |
    dotnet test WebService/WebService.sln --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run Tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appName)
    package: $(Build.ArtifactStagingDirectory)
    resourceGroupName: $(resourceGroupName)
    appType: 'webAppLinux'