trigger:
- main  # Adjust this to your default branch

pool:
  name: 'Default'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'Visual Studio Enterprise Subscription – MPN(61111058-5a97-4680-b52e-9ab2dcc700f7)'
  appName: 'lonwebapp'
  resourceGroupName: 'az400'

steps:
- script: |
    dotnet restore WebService/WebService.sln
  displayName: 'Restore NuGet Packages'

- script: |
    dotnet build WebService/WebService.sln --configuration $(buildConfiguration)
  displayName: 'Build Solution'

- script: |
    dotnet test WebService/WebService.sln --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run Tests'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/WebService/bin/Release/net8.0/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build_output.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/build_output.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appName)
    package: '$(Build.ArtifactStagingDirectory)/build_output.zip'
    resourceGroupName: $(resourceGroupName)
    appType: 'webAppLinux'