trigger:
- main  # Adjust this to your default branch

pool:
  vmImage: 'Default'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'  # Use the latest version of .NET Core 8.0 SDK
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    dotnet restore WebService/WebService.sln
  displayName: 'Restore NuGet Packages'

- script: |
    dotnet build WebService/WebService.sln --configuration $(buildConfiguration)
  displayName: 'Build Solution'

- script: |
    dotnet test WebService/WebService.sln --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run Tests'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'